package com.shapeshed.booth.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.shapeshed.booth.data.PodcastEntity
import com.shapeshed.booth.data.PodcastSubscriptionsViewMode

@Composable
internal fun PodcastSubscriptionsContent(
    podcasts: List<PodcastEntity>,
    latestEpisodePublishedAt: Map<Long, Long?>,
    viewMode: PodcastSubscriptionsViewMode,
    onViewModeChange: (PodcastSubscriptionsViewMode) -> Unit,
    sortOrder: PodcastSortOrder,
    onSortOrderChange: (PodcastSortOrder) -> Unit,
    state: PodcastHomeState,
    showSearch: Boolean,
    directFeedUrl: String,
    onDirectFeedUrlChange: (String) -> Unit,
    onSubscribeDirect: () -> Unit,
    onQueryChange: (String) -> Unit,
    onSearch: () -> Unit,
    onPodcastClick: (Long) -> Unit,
    onRemovePodcast: (PodcastEntity) -> Unit,
    onSearchResultClick: (String) -> Unit,
    onOpenSearch: () -> Unit,
    onImportOpml: () -> Unit,
    importProgress: PodcastImportProgress?,
    popularPodcasts: List<com.shapeshed.booth.data.PodcastSearchResult>,
    isLoadingPopular: Boolean,
    onOpenPopularPodcast: (com.shapeshed.booth.data.PodcastSearchResult) -> Unit,
    selectedCategory: com.shapeshed.booth.data.PodcastDiscoveryCategory? = null,
    categoryResults: List<com.shapeshed.booth.data.PodcastSearchResult> = emptyList(),
    categoryResultsById: Map<String, List<com.shapeshed.booth.data.PodcastSearchResult>> = emptyMap(),
    isLoadingCategory: Boolean = false,
    onCategorySelected: (com.shapeshed.booth.data.PodcastDiscoveryCategory?) -> Unit = {},
    onPreloadCategory: (com.shapeshed.booth.data.PodcastDiscoveryCategory) -> Unit = {},
    categories: List<com.shapeshed.booth.data.PodcastDiscoveryCategory> = emptyList(),
    onRefresh: () -> Unit,
    refreshing: Boolean,
    modifier: Modifier = Modifier,
) {
    PodcastLibrary(
        podcasts = podcasts,
        latestEpisodePublishedAt = latestEpisodePublishedAt,
        viewMode = viewMode,
        onViewModeChange = onViewModeChange,
        sortOrder = sortOrder,
        onSortOrderChange = onSortOrderChange,
        state = state,
        showSearch = showSearch,
        directFeedUrl = directFeedUrl,
        onDirectFeedUrlChange = onDirectFeedUrlChange,
        onSubscribeDirect = onSubscribeDirect,
        onQueryChange = onQueryChange,
        onSearch = onSearch,
        onPodcastClick = onPodcastClick,
        onRemovePodcast = onRemovePodcast,
        onSearchResultClick = onSearchResultClick,
        onOpenSearch = onOpenSearch,
        onImportOpml = onImportOpml,
        importProgress = importProgress,
        popularPodcasts = popularPodcasts,
        isLoadingPopular = isLoadingPopular,
        onOpenPopularPodcast = onOpenPopularPodcast,
        selectedCategory = selectedCategory,
        categoryResults = categoryResults,
        categoryResultsById = categoryResultsById,
        isLoadingCategory = isLoadingCategory,
        onCategorySelected = onCategorySelected,
        onPreloadCategory = onPreloadCategory,
        categories = categories,
        onRefresh = onRefresh,
        refreshing = refreshing,
        modifier = modifier,
    )
}
