org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.incremental=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.experimental.enableScreenshotTest=true
